### ISSUE TITLE
any chance for an android app package?

### ISSUE THREAD

**Issue by ERamseth** [sodenn/2do-txt#1178]
My wife is using this app on her iPhone and I really like it. Any chance for an android package? I think an offline PWA should (?) be able to install from browser, but I tried Firefox and Cromite (chromium fork) and neither offered the install option.

**Comment by ERamseth** [comment]
Update: I guess "add to home screen" is the new "install"? Haven't tried offline yet. Otherwise it's working fine.

The only added thing that would be nice is directly opening and saving files rather than "import" and "export" (unless that's supposed to be there and I'm missing it?)

**Comment by sodenn** [comment]
Hi @ERamseth. Due to limitations in mobile browsers and their sandboxing, saving files directly to a local file system isn’t possible on iOS or Android in the same way it works on desktop. For now, my focus will remain on further developing the web/PWA version of the app. Which is why I am currently not planning any further development of separate mobile apps.
In the future, I’m considering the possibility of a self-hosted Docker solution, which would allow users to save Todo files directly to a shared volume on a server. This would make it possible to save files across devices. However, this idea is still in its early stages and would require more planning.

**Comment by ERamseth** [comment]
> Hi @ERamseth. Due to limitations in mobile browsers and their sandboxing, saving files directly to a local file system isn’t possible on iOS or Android in the same way it works on desktop. For now, my focus will remain on further developing the web/PWA version of the app. Which is why I am currently not planning any further development of separate mobile apps. 

So is the ios app that uses the files backend deprecated?
