### ISSUE TITLE
Sync with Files on iOS

### ISSUE THREAD

**Issue by nielsk** [sodenn/2do-txt#770]
Any chance to have it work with "Files" on iOS, so that it can be used with Working Copy (which is a git-client - https://workingcopy.app)? 

Then I could create a shortcut that will commit/push on closing the app and pull on opening.

**Comment by sodenn** [comment]
Hi @nielsk. Since version v1.5 there is a **2do.txt** folder in the Files app. 2do.txt uses the `UIFileSharingEnabled` and `LSSupportsOpeningDocumentsInPlace` key to enable local file sharing (see https://developer.apple.com/documentation/fileprovider#2918905). So I would have thought that this is already possible 🤔.

**Comment by nielsk** [comment]
Ok. I can use a feature of working copy to make this work. Thanks.
